name: run-tests

on: [push, pull_request]

env:
  VROOM_VERSION: 0.14.0

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        vim-flavour: [vim, neovim]
        maktaba-version: [master]
        include:
          - os: ubuntu-22.04
            vim-flavour: neovim
            maktaba-version: 1.1.1
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install vim
        if: ${{ matrix.vim-flavour == 'vim' }}
        run: |
          sudo apt update
          sudo apt install vim vim-gtk xvfb
      - name: Install neovim
        if: ${{ matrix.vim-flavour == 'neovim' }}
        run: |
          sudo apt update
          sudo apt install neovim python3-neovim xvfb
      - name: Install vroom
        run: |
          wget https://github.com/google/vroom/releases/download/v${VROOM_VERSION}/vroom_${VROOM_VERSION}-1_all.deb
          sudo dpkg -i ./vroom_${VROOM_VERSION}-1_all.deb
      - name: Install plugin dependencies
        run: |
          git clone -b ${{ matrix.maktaba-version }} https://github.com/google/vim-maktaba.git ../maktaba/

      - name: Run tests (vim)
        if: ${{ matrix.vim-flavour == 'vim' }}
        timeout-minutes: 10
        run: |
          xvfb-run script -q -e -c 'vroom --crawl'
      - name: Run tests (neovim)
        if: ${{ matrix.vim-flavour == 'neovim' }}
        timeout-minutes: 2
        run: |
          xvfb-run script -q -e -c 'vroom --neovim --crawl'
        continue-on-error: true
